export const mySkills = [
    "JavaScript",
    "React.js",
    "Next.js",
    "Redux Toolkit",
    "Context API",
    "CSS3",
    "Tailwind CSS",
    "Bootstrap",
    "HTML5",
    "Responsive Design",
    "Version Control (Git)",
    "GitHub",
    "Framer Motion",
    "RESTful API",
    "Shadcn UI",
    "Axios",
    "React Router",
    "Vite",
    "Figma",
    "Chart.js",
    "TypeScript",
    "Problem-Solving",
    "Time Management",
    "Communication",
    "Agile Methodologies",
    "Collaboration",
  ];
  